music/urls.py
from django.conf.urls import url
from . import views


app_name = 'music'

# urlpatterns = [
#     url(r'^$', views.index , name='index'),
#     url(r'^add/$', views.add , name='add'),
#     url(r'^(?P<album_id>[0-9]+)$', views.detail, name='detail'),  
#     url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'), 
# ]


urlpatterns = [
    url(r'^$', views.IndexView.as_view() , name='index'),
    url(r'^register/$', views.UserFormView.as_view() , name='register'),
    url(r'^login/$', views.LoginFormView.as_view() , name='login'),
    url(r'^logout/$', views.LogoutView.as_view() , name='logout'),
    url(r'^(?P<pk>[0-9]+)$', views.DetailView.as_view(), name='detail'),  
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
   
]

website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
	url(r'^$', views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo= models.FileField()


	def get_absolute_url(self):
		return reverse('music:detail', kwargs={'pk':self.pk})

	def __str__(self):
		return self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type  = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	song_url   = models.CharField(max_length=400) 
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

music/forms.py
from django.contrib.auth.models import User 
from django import forms 


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	email = forms.CharField()
	class Meta:
		model = User
		fields =  ['username','email','password']



class LoginForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)	
	class Meta:
		model = User
		fields =  ['username','password']

music/views.py
# from django.shortcuts import render, get_object_or_404
# from .models import Album,Song


# def index(request):
# 	all_albums = Album.objects.all()
# 	context = {'all_albums': all_albums}
# 	return render(request ,'music/index.html',context)


# def add(request):
# 	# data = Album()
# 	# data.artist = "Arjit Singh"
# 	# data.album_title = "Arjit"
# 	# data.genre = "MP3"
# 	# data.album_logo = "http://www.mazale.in/wp-content/uploads/2016/02/arijit-singh.jpg"
# 	# data.save()
# 	return HttpResponse('Added')


# def detail(request, album_id):
# 	#album = Album.objects.get(pk=album_id)
# 	album = get_object_or_404(Album,pk=album_id)
# 	return render(request , 'music/detail.html',{'album':album})
	
	
# def favorite(request, album_id):
# 	album = get_object_or_404(Album,pk=album_id)
# 	try:
# 		selected_song = album.song_set.get(pk=request.POST['song'])
# 	except(KeyError, Song.DoesNotExist):
# 		return render(request , 'music/detail.html',{
# 			'album':album,
# 			'error_message': "Song not selected"
# 			})
# 	else:
# 		selected_song.is_favorite=True
# 		selected_song.save()
# 		return render(request , 'music/detail.html',{'album':album})





# CLASS BASED VIEWS


from django.views import generic
from .models import Album
from django.views.generic.edit import CreateView, UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login , logout
from django.views.generic import View
from .forms import UserForm, LoginForm


class IndexView(generic.ListView):
	template_name = 'music/index.html'


	def get_queryset(self):
		return Album.objects.all()


class DetailView(generic.DetailView):
	model = Album
	template_name = 'music/detail.html'



class AlbumCreate(CreateView):
	model = Album	
	fields = ['artist','album_title','genre','album_logo']
	


class AlbumUpdate(UpdateView):
	model = Album	
	fields = ['artist','album_title','genre','album_logo']


class AlbumDelete(DeleteView):
	model = Album	
	success_url = reverse_lazy('music:index')


class UserFormView(View):
	form_class = UserForm
	template_name = 'music/registration_form.html'


	def get(self,request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form':form})



	# process form data	
	def post(self,request):
		form = self.form_class(request.POST)


		if form.is_valid():
			user = form.save(commit=False)

	
			# cleaned data
			username = form.cleaned_data['username']
			email 	 = form.cleaned_data['email']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			# returns user objects if credentials are correct
			user = authenticate(username=username,password=password)

			if user is not None:

				if user.is_active:

					login(request,user)
					return redirect('music:index')

		return render(request, self.template_name, {'form':form})




# Logic for LoggingIn

class LoginFormView(View):
	form_class = LoginForm
	template_name = 'music/login_form.html'


	def get(self,request):
		if request.user.is_authenticated():
			return redirect('music:index')			
		else:
			form = self.form_class(None)
			return render(request, self.template_name, {'form':form})




	# process login-form data	
	def post(self,request):
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)

		if user is not None:
			 login(request, user)
			 return redirect('music:index')

		return render(request, self.template_name, {'form':form})



class LogoutView(View):

    def get(self, request):
    	logout(request)
    	return redirect('music:index')

website/views.py
from django.shortcuts import render

def index(request):
	return render(request,'index.html')

music/templates/music/album_form.html
{%  extends 'layouts.html' %}
{% load static %}

{% block content %}

 <div class="row">
<div class="col m4"></div>
    <form class="col s8" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% include 'music/form-template.html' %}

    


	   <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
  </button> 
    </form>
  </div>

  <div class="col m4"></div>
        

{% endblock %}

music/templates/music/detail.html
{%  extends 'layouts.html' %}
{% load static %}

{% block content %}

<div class="container">

<h3>{{album.album_title}}</h3>
<div class="row">
	<div class="col s4 m4 l4">
	  <div class="card z-depth-3">
	    <div class="card-image">
	      <img src="{{album.album_logo.url}}">           
	    </div> 
	  </div>
	</div>

	<div class="col l8">
	 <h3 class="flow-text">{{album.artist}}</h3>

	
	
	

	<table class="bordered">       
        <tbody>
        {% for song in album.song_set.all %}
          <tr>
            <td class="green-text"><strong>{{song.song_title}}</strong></td>
            <td>
            <div class="chip">
  		 		{{song.file_type}}    			
  			</div>
  			</td>
            <td>
            <audio controls>			 
			  <source src="{{song.song_url}}" type="audio/mpeg">
			Your browser does not support the audio element.
			</audio>
			</td>
          </tr>
         {% endfor %} 
        </tbody>
      </table>

      </div>
	
 </div><!--end of row-->

</div><!--end of container-->



{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
<span class="red-text">{{field.errors}}</span>

	  <div class="row">
        <div class="input-field col s6">
          {{ field }}
          {{ field.label_tag }}
        </div>     
      </div>    

{% endfor %}

music/templates/music/index.html
{%  extends 'layouts.html' %}
{% load static %}

{% block content %}
	<!--

	{% for album in all_albums  %}

		<li><a href="{% url 'music:detail' album.id %}">{{album.album_title}}</a></li>

	{% endfor %}

	 -->

<center>{% if request.user.is_authenticated %}<h3 class="flow-text"><strong>Welcome {{ request.user.username }}</strong> || <a href="{% url 'music:logout' %}">LOGOUT</a></h3>
{% else %}<a href="{% url 'music:login' %}"><h3 class="flow-text"><strong><span class="grey-text darken-3">LOGIN</span></strong></h3></a>{% endif %}
</center>
<div class="row">

{% for album in object_list  %}

        <div class="col l3">
              <a href="{% url 'music:detail' album.id %}">
                  <img src="{{album.album_logo.url}}" class="responsive-img">  
              </a>   

               <a class="btn waves-effect waves-light  green accent-4" href="{% url 'music:album-update' album.id %}">
               EDIT
               </a>   


               <form class="col s8" action="{% url 'music:album-delete' album.id %}" method="post">
    			
    			{% csrf_token %}
    				<input type="hidden" name="album_id" value="{{album.id}}">
				   <center><button class="center-align btn waves-effect waves-light" type="submit" name="action">DELETE		    		
			  	   </button> 
			  	   </center>
    			</form>


        </div>

{% endfor %}  

</div><!--end of row-->


      

   

 
          

{% endblock %}

music/templates/music/login_form.html
{%  extends 'layouts.html' %}
{% load static %}

{% block content %}
<p class="red-text flow-text center-align">LOGIN</p>
 <div class="row">
<div class="col m4"></div>
    <form class="col s8" action="" method="post">
    {% csrf_token %}

    {% include 'music/form-template.html' %}


	   <button class="btn waves-effect waves-light light-blue accent-4" type="submit" name="action">LOGIN
    
  </button> 
    </form>
  </div>

  <div class="col m4"></div>
        

{% endblock %}

music/templates/music/registration_form.html
{%  extends 'layouts.html' %}
{% load static %}

{% block content %}
<p class="red-text flow-text center-align">Create a new account</p>
 <div class="row">
<div class="col m4"></div>
    <form class="col s8" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% include 'music/form-template.html' %}

    


	   <button class="btn waves-effect waves-light light-blue accent-4" type="submit" name="action">REGISTER
    
  </button> 
    </form>
  </div>

  <div class="col m4"></div>
        

{% endblock %}

templates/index.html
{%  extends 'layouts.html' %}
{% load static %}



{% block content %}

<div class="row center">
<h5 class="header col s12 light">One good thing about music, when it hits you, you feel no pain.</h5><br>
<div class="row">
<div class="col s4">
	<img src="https://d13yacurqjgara.cloudfront.net/users/2081/screenshots/2901028/castro_2.gif" class="responsive-img">
</div>
<div class="col s4">
	<img src="{% static 'images/sing.png' %}" class="responsive-img">
</div>
<div class="col s4">
	<img src="https://d13yacurqjgara.cloudfront.net/users/51395/screenshots/1353765/audioplayer01.gif" class="responsive-img">
</div>
</div>
</div>

  <div class="row center">
   <a href="/music" class="btn-large waves-effect waves-light light-blue">EXPLORE MUSIC</a>

   <a href="{% url 'music:album-add' %}" class="btn-large waves-effect waves-light light-green">ADD ALBUM </a>


   <a href="{% url 'music:register' %}" class="btn-large waves-effect waves-light red accent-3">REGISTER </a>


   <a href="{% url 'music:login' %}" class="btn-large waves-effect waves-light brown accent-3">LOGIN</a>

  </div>
 <br><br>


{% endblock %}

templates/layouts.html
{% load static %}
 <!DOCTYPE html>
  <html>
    <head>    
      
      <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>     
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <style type="text/css">
      body{
           background: url("{% static 'images/background.jpg' %}") no-repeat center center fixed; 
          -webkit-background-size: cover;
          -moz-background-size: cover;
          -o-background-size: cover;
          background-size: cover;
      }
    </style>

    <body>
    
      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>

      <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      
      <h3 class="header center red-text"><a href="/"><span class="purple-text darken-4">MUSIC LIBRARY</span></a></h3>
        

    </div>
  </div>


      {% block content %} {% endblock %}

    </body>
  </html>
        